Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/xenial64"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 1024
    vb.cpus = 1
  end

  config.vm.define :phpbase, primary: true do |web|
    web.vm.network "private_network", ip: "172.28.128.3"
    web.vm.provision "main", type: "ansible" do |ansible|
      ansible.verbose = "-v"
      ansible.playbook = "playbooks/wordpress.yml"
    end
  end

end
